chartmogul/api/invoice.py

Fixes https://github.com/chartmogul/chartmogul-python/issues/6

Allow due_date to be excluded from invoice

---

README.md
chartmogul/__init__.py
chartmogul/api/invoice.py
test/api/test_invoice.py

* fitted new endpoint inside `Invoice.all`

DP-311: Add new list invoices endpoint

---

chartmogul/__init__.py
chartmogul/api/invoice.py
test/api/test_invoice.py

[DP-309] support for Delete Invoice

---

README.md
chartmogul/__init__.py
chartmogul/api/invoice.py
test/api/test_invoice.py

* adding retrieve action
* covered with basic unit test

[DP-468] Retrieve Invoice endpoint

---

chartmogul/__init__.py
chartmogul/api/invoice.py

* change of schema for Invoice response

[DP-495] new optional parameter data_source_uuid on Invoice

---

fixtures/delete_invoice.yaml
setup.py
test/integration/test_delete_invoice
test/integration/test_delete_invoice.py

* added a new class of tests: integration with VCR
* this case tests data source, customer, plan & invoice creation & invoice deletion.
* automatically removes credentials

First integration test with VCR for python library

---

chartmogul/api/subscription.py
test/api/test_subscription.py

* list result didn't contain the `customer_uuid`
* adding a test

[ch543] add customer_uuid in result of list_imported

---

.travis.yml
README.md
chartmogul/__init__.py
chartmogul/api/invoice.py

Add transaction_fees_in_cents [ch3025]

---

chartmogul/__init__.py
requirements.txt
setup.py

Fix marshmallow version to `marshmallow>=2.12.1,<3`

Fix version of marshmallow to version 2.* [ch15346]

---

chartmogul/__init__.py
chartmogul/api/invoice.py
test/api/test_invoice.py

Added support for an optional customer_external_id attribute of Invoices#create endpoint

Allow customer_external_id field [ch15586]

---

.travis.yml
README.md
setup.py

* verify compatibility with 3.9
* use `pip3` and `python3` in examples
* update tags
(the marschmallow update was merged in #39 I've just spotted there are some metadata to update)

Update readme + python 3.9 [ch28619]

---

chartmogul/__init__.py
chartmogul/api/transaction.py
test/api/test_invoice.py

https://app.clubhouse.io/chartmogul/story/28623/add-transaction-amount-to-chartmogul-python

Add transaction amount [ch28623]

---

README.md
chartmogul/__init__.py
chartmogul/api/config.py
test/api/test_account.py
test/api/test_activities_export.py
test/api/test_activity.py
test/api/test_common.py
test/api/test_custom_attrs.py
test/api/test_customer.py
test/api/test_customers/test_activity.py
test/api/test_customers/test_subscription.py
test/api/test_data_source.py
test/api/test_invoice.py
test/api/test_metrics.py
test/api/test_ping.py
test/api/test_plan.py
test/api/test_plan_group.py
test/api/test_retry_request.py
test/api/test_tags.py
test/integration/test_delete_invoice.py

- Update Config to use `api_key` instead of `account_token`/`secret_key` combo
- Bump version to 3.0.0

Introduce new auth method [sc-35184]

---

requirements.txt
setup.py

Update version of future egg with the one with security updates

Add newest future version

---

.flake8
README.md
chartmogul/__init__.py
chartmogul/api/contact.py
chartmogul/api/customer.py
chartmogul/resource.py
chartmogul/retry_request.py
test/api/test_contact.py
test/api/test_customer.py

This should add support for Contacts (https://dev.chartmogul.com/reference/contacts). Also adds the related items in the Customers resource (https://dev.chartmogul.com/reference/customers).

Support for Contacts

---

chartmogul/api/subscription_event.py
test/api/test_subscription_event.py

Add Event Order property added for Subscription Event's.

Add event order to subscription event

---

README.md
chartmogul/__init__.py
chartmogul/api/customer.py
chartmogul/api/opportunity.py
test/api/test_customer.py
test/api/test_opportunity.py

closes ticket: https://app.shortcut.com/chartmogul/story/57430/support-opportunities-resource-python-client
API Specs: https://www.notion.so/chartmogul/API-endpoints-for-Opportunities-a92323514bf44f89ad2f97ae30cee7f0#6f09cc7a71bc40e69ef65d8d0342d230
Customers
```
chartmogul.Customer.opportunities(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', cursor='aabbcc', per_page=20)
chartmogul.Customer.createOpportunity(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', data={})
```
```
chartmogul.Opportunity.create(config, data={})
chartmogul.Opportunity.all(config, cursor='aabbcc', per_page=20, customer_uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb')
chartmogul.Opportunity.retrieve(config, uuid='note_5915ee5a-babd-406b-b8ce-d207133fb4cb')
chartmogul.Opportunity.patch(config, …
```

feat(sc-57430): Support Opportunities API

---

.github/workflows/test.yml
README.md
chartmogul/api/customer.py
test/api/test_customer.py

Story details: https://app.shortcut.com/chartmogul/story/62680
This PR adds support for the customer unmerge API endpoint.

[sc-62680] SDK Unmerge Support - Python

---

CHANGELOG.md

Story details: https://app.shortcut.com/chartmogul/story/66235
Update changelog to reflect changes released in version 4.5.0.

[sc-66235] Update changelog for v4.5.0

---

requirements.txt
setup.py

https://github.com/chartmogul/chartmogul-python/issues/107

Stick marshmallow to 3 version
